import { test, expect } from '@playwright/test'

test('homepage question, exact aliases and search back state', async ({ page }) => {
  await page.goto('./search')
  const input = page.getByRole('searchbox')
  await input.fill('怎么复活')
  await expect(page.locator('.search-result')).not.toHaveCount(0)
  await expect(page).toHaveURL(/q=/)
  await page.locator('.search-result').filter({ has: page.getByRole('heading', { name: '告密的心' }) }).click()
  await expect(page).toHaveURL(/wiki\/tell-tale-heart/)
  await page.goBack()
  await expect(input).toHaveValue('怎么复活')
  await page.reload()
  await expect(input).toHaveValue('怎么复活')
  await input.fill('机器人')
  await expect(page.locator('.search-result h2').first()).toHaveText('WX-78')
})

test('search continues beyond twelve and preserves loaded results', async ({ page }) => {
  await page.goto('./search?q=料理')
  await expect(page.locator('.search-result')).toHaveCount(12)
  await expect(page.locator('.result-count strong')).toHaveText(/5[0-9]/)
  await page.getByRole('button', { name: '加载更多结果' }).click()
  await expect(page.locator('.search-result')).toHaveCount(24)
  await page.locator('.search-result').nth(18).click()
  await expect(page).toHaveURL(/wiki\//)
  await page.goBack()
  await expect(page.locator('.search-result')).toHaveCount(24)
})

test('catalog pagination, filters, reload and back restore', async ({ page }) => {
  await page.goto('./wiki')
  await expect(page.locator('.wiki-catalog-item')).toHaveCount(24)
  await page.getByRole('button', { name: '料理', exact: true }).click()
  await expect(page.locator('.catalog-summary')).toContainText('50 条')
  await page.getByRole('link', { name: '下一页', exact: true }).click()
  await expect(page.locator('.catalog-summary')).toContainText('第 2 / 3 页')
  const title = await page.locator('.wiki-catalog-item h2').first().textContent()
  await page.locator('.wiki-catalog-item').nth(5).scrollIntoViewIfNeeded()
  const position = await page.evaluate(() => scrollY)
  await page.locator('.wiki-catalog-item').nth(5).click()
  await expect(page).toHaveURL(/wiki\//)
  await page.goBack()
  await expect(page.locator('.wiki-catalog-item h2').first()).toHaveText(title!)
  await expect(page.getByRole('button', { name: '料理', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect.poll(() => page.evaluate(() => scrollY)).toBeGreaterThan(Math.max(0, position - 180))
  await page.reload()
  await expect(page.locator('.catalog-summary')).toContainText('第 2 / 3 页')
  await page.getByLabel('料理用途').selectOption('health')
  await expect(page.locator('.catalog-summary')).toContainText('第 1 /')
  await expect(page.locator('.wiki-catalog-item')).not.toHaveCount(0)
})

test('deep-linked catalog hydrates without mismatches and handles empty states', async ({ page }) => {
  const hydration: string[] = []
  page.on('console', message => { if (/hydration/i.test(message.text())) hydration.push(message.text()) })
  await page.goto('./wiki?category=料理&benefit=health&ingredient=树枝')
  await expect(page.getByLabel('料理用途')).toHaveValue('health')
  await expect(page.getByLabel('示例食材')).toHaveValue('树枝')
  await page.getByRole('searchbox').fill('zzzznomatch')
  await expect(page.getByRole('heading', { name: '没有匹配的档案' })).toBeVisible()
  await page.getByRole('link', { name: '清除全部筛选' }).click()
  await expect(page.locator('.wiki-catalog-item')).toHaveCount(24)
  expect(hydration).toEqual([])
})

test('old progress persists and every advanced route is available', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('campfire-wiki:progress:v1', JSON.stringify(['gather-basics', 'lunar-tech'])))
  await page.goto('./tools/progression-checklist')
  await expect(page.locator('.route-checklist')).toHaveCount(9)
  await expect(page.locator('.route-checklist li')).toHaveCount(31)
  await expect(page.locator('.route-checklist li > button[aria-pressed="true"]')).toHaveCount(2)
  await page.getByLabel('当前推进方向').selectOption('shadow-sanctum')
  await expect(page.locator('.route-checklist li')).toHaveCount(3)
  await expect(page.locator('.next-step h2')).toContainText('织影者')
  await page.locator('.route-checklist li > button').first().click()
  await expect(page.locator('.next-step h2')).toContainText('圣所')
})

test('progress saves, reset cancel is safe, confirm clears', async ({ page }) => {
  await page.goto('./tools/progression-checklist')
  const first = page.locator('.route-checklist li > button').first()
  await first.click()
  await page.reload()
  await expect(first).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '重置全部进度', exact: true }).click()
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await expect(first).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '重置全部进度', exact: true }).click()
  await page.getByRole('button', { name: '确定重置', exact: true }).click()
  await expect(first).toHaveAttribute('aria-pressed', 'false')
})

test('search shortcut and mobile menu keyboard behavior', async ({ page }) => {
  await page.goto('./', { waitUntil: 'networkidle' })
  await page.keyboard.press('/')
  await expect(page.getByRole('searchbox')).toBeFocused()
  await page.getByRole('searchbox').fill('羊')
  await page.keyboard.press('/')
  await expect(page.getByRole('searchbox')).toHaveValue('羊/')
  await page.setViewportSize({ width: 375, height: 812 })
  await expect(page.getByRole('link', { name: '搜索攻略', exact: true })).toBeVisible()
  const menu = page.getByRole('button', { name: '切换导航' })
  await menu.click()
  await expect(page.locator('#mobile-menu')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('#mobile-menu')).toHaveCount(0)
  await expect(menu).toBeFocused()
})

test('article contents and dossier anchors work', async ({ page }) => {
  await page.goto('./progression/shadow-sanctum')
  await page.locator('.article-toc summary').click()
  await page.getByRole('navigation', { name: '文章章节' }).getByRole('link', { name: '守卫塔战', exact: true }).click()
  await expect(page).toHaveURL(/#/)
  await page.goto('./wiki/pierogi')
  await expect(page.locator('main')).toHaveCount(1)
  await page.getByRole('navigation', { name: '档案章节' }).getByRole('link', { name: '配方' }).click()
  await expect(page).toHaveURL(/#dish-title/)
  await expect.poll(() => page.locator('#dish-title').evaluate(el => el.getBoundingClientRect().top)).toBeGreaterThan(60)
})

test('Boss directory, canonical, sitemap and Chinese 404', async ({ page, request }) => {
  await page.goto('./bosses')
  await expect(page.locator('.content-card')).toHaveCount(15)
  await page.locator('.content-card').filter({ has: page.getByRole('heading', { name: '天体英雄' }) }).click()
  await expect(page).toHaveURL(/wiki\/celestial-champion/)
  await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href', 'https://fshfish88-lab.github.io/jihuang/wiki/celestial-champion/')
  await expect(page.locator('meta[property="og:image"]')).toHaveAttribute('content', /^https:\/\//)
  const sitemap = await request.get('./sitemap.xml')
  expect(sitemap.status()).toBe(200)
  expect(await sitemap.text()).toContain('/wiki/keystone/')
  const missing = await page.goto('./not-a-real-page')
  expect(missing?.status()).toBe(404)
  await expect(page.getByRole('heading', { name: '这页手记，似乎迷路了。' })).toBeVisible()
  await page.getByRole('link', { name: '回到首页' }).click()
  await expect(page.locator('.hero')).toBeVisible()
})
